# Generated by Django 4.2.4 on 2023-08-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fristname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('dob', models.DateField()),
            ],
        ),
    ]
